import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
  copyFileSync,
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { join, parse, relative, resolve, sep } from 'node:path';

const [variant = 'debug', architecture = 'x86_64'] = process.argv.slice(2);
const allowedVariants = new Set(['debug', 'release']);
const allowedArchitectures = new Set(['x86_64', 'arm64-v8a']);

if (!allowedVariants.has(variant) || !allowedArchitectures.has(architecture)) {
  throw new Error('Usage: node scripts/android-build.mjs <debug|release> <x86_64|arm64-v8a>');
}

const sourceRoot = resolve(import.meta.dirname, '..');
const isWindows = process.platform === 'win32';
const buildEnv = {
  ...process.env,
  NODE_ENV: variant === 'release' ? 'production' : 'development',
  ORG_GRADLE_PROJECT_reactNativeArchitectures: architecture,
};

function run(command, args, cwd, env = buildEnv) {
  const result = spawnSync(command, args, { cwd, env, stdio: 'inherit' });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    throw new Error(`${command} exited with code ${result.status ?? 'unknown'}`);
  }
}

function prepareShortWindowsStage() {
  const stageRoot = resolve(
    process.env.SHIFTPROOF_ANDROID_STAGE?.trim()
      || join(parse(sourceRoot).root, 'shiftproof-native-stage'),
  );
  const marker = join(stageRoot, '.shiftproof-native-stage');

  if (existsSync(stageRoot) && !existsSync(marker)) {
    throw new Error(
      `Refusing to replace ${stageRoot} because it is not a ShiftProof build stage. `
      + 'Set SHIFTPROOF_ANDROID_STAGE to another short, disposable directory.',
    );
  }
  if (existsSync(stageRoot)) rmSync(stageRoot, { recursive: true, force: true });
  mkdirSync(stageRoot, { recursive: true });

  const excludedTopLevel = new Set([
    '.claude',
    '.expo',
    '.git',
    'android',
    'dist',
    'ios',
    'node_modules',
  ]);
  cpSync(sourceRoot, stageRoot, {
    recursive: true,
    filter(source) {
      const pathFromRoot = relative(sourceRoot, source);
      if (!pathFromRoot) return true;
      return !excludedTopLevel.has(pathFromRoot.split(sep)[0]);
    },
  });
  writeFileSync(marker, 'Generated by ShiftProof Android build. Safe to replace.\n');

  if (isWindows) {
    run('cmd.exe', ['/d', '/s', '/c', 'npm.cmd ci'], stageRoot);
  } else {
    run('npm', ['ci'], stageRoot);
  }
  return stageRoot;
}

// Ninja still rejects generated paths beyond 260 characters on Windows. Build
// from a guarded short-path stage while keeping all source and outputs here.
const shouldStage = isWindows && sourceRoot.length > 60;
const buildRoot = shouldStage ? prepareShortWindowsStage() : sourceRoot;
const expoCli = join(buildRoot, 'node_modules', 'expo', 'bin', 'cli');
if (!existsSync(expoCli)) {
  throw new Error(`Expo CLI is missing at ${expoCli}. Run npm ci in apps/mobile first.`);
}

run(process.execPath, [expoCli, 'prebuild', '--platform', 'android', '--no-install'], buildRoot);

const task = variant === 'release' ? 'assembleRelease' : 'assembleDebug';
const androidRoot = join(buildRoot, 'android');
if (isWindows) {
  run(
    'cmd.exe',
    ['/d', '/s', '/c', `gradlew.bat ${task} -PreactNativeArchitectures=${architecture}`],
    androidRoot,
  );
} else {
  run('./gradlew', [task, `-PreactNativeArchitectures=${architecture}`], androidRoot);
}

const source = join(
  androidRoot,
  'app',
  'build',
  'outputs',
  'apk',
  variant,
  `app-${variant}.apk`,
);
if (!existsSync(source)) throw new Error(`Expected APK not found: ${source}`);

const destinationDir = join(sourceRoot, 'dist', 'android');
mkdirSync(destinationDir, { recursive: true });
const destination = join(destinationDir, `shiftproof-${variant}-${architecture}.apk`);
copyFileSync(source, destination);

const checksum = createHash('sha256').update(readFileSync(destination)).digest('hex').toUpperCase();
console.log(`APK: ${destination}`);
console.log(`SHA-256: ${checksum}`);

if (shouldStage && process.env.SHIFTPROOF_KEEP_ANDROID_STAGE !== '1') {
  rmSync(buildRoot, { recursive: true, force: true });
}
